server.port=${SERVER_PORT:8081}

spring.datasource.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=solutis
spring.datasource.password=solutis

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true